Feature/apibug 細かい部分の修正
g0tiu5a/ctftime pull request #4
Opened 2017-08-30 09:00 UTC by tukeJonny

変数の公開、型名周りなどの細かい修正を加えました。
確認よろしくお願いいたします。

2017-08-31 15:23 UTC, ryosan-470 commented on _examples/events.go
> +	for idx, event := range events.(ctftime.Events) {
こういう書き方ができるんですね。(知らんかった)

2017-08-31 15:24 UTC, ryosan-470 requested changes
.api.go.swp を消しましょう。ほかは 🙆

2017-08-31 15:36 UTC, tukeJonny commented
ごめんなさい・・・
swpファイルは消していたつもりだったのに・・・

直しまする

2017-08-31 15:38 UTC, tukeJonny commented on _examples/events.go
> +	for idx, event := range events.(ctftime.Events) {
interface型に抽象化しているので、型アサーションが必要になってきます〜

2017-09-01 03:23 UTC, ryosan-470 approved these changes

2017-09-01 03:23 UTC, merged